sudo: required
language: go
services:
- docker
script:
  - make bootstrap
  - make test
notifications:
  slack:
    rooms:
      - drycc:xKmLlmJR4hfRAgVIOwdpAoC9#drycc
after_success:
  - bash <(curl -s https://codecov.io/bash)
