sudo: required
language: go
services:
- docker
script:
  - DEV_REGISTRY="docker.io" make bootstrap
  - DEV_REGISTRY="docker.io" make test
  - DEV_REGISTRY="docker.io" make test-cover
notifications:
  slack:
    rooms:
      - drycc:xKmLlmJR4hfRAgVIOwdpAoC9#drycc
after_success:
  - bash <(curl -s https://codecov.io/bash)
