apiVersion: v1
kind: Secret
metadata:
  name: builder-secret
  labels:
    heritage: drycc
type: Opaque
data:
  {{- if (.Values.registryHost) }}
  registry-host: {{ .Values.registryHost | b64enc }}
  registry-username: {{ .Values.registryUsername | b64enc }}
  registry-password: {{ .Values.registryPassword | b64enc }}
  registry-organization: {{ .Values.registryOrganization | b64enc }}
  {{- end }}
  {{- if (.Values.storageEndpoint) }}
  storage-lookup: {{ .Values.storageLookup | b64enc }}
  storage-bucket: {{ .Values.storageBucket | b64enc }}
  storage-endpoint: {{ .Values.storageEndpoint | b64enc }}
  storage-accesskey: {{ .Values.storageAccesskey | b64enc }}
  storage-secretkey: {{ .Values.storageSecretkey | b64enc }}
  {{- end }}
