apiVersion: v1
kind: Service
metadata:
  name: drycc-builder
  labels:
    heritage: drycc
spec:
  ports:
    - name: ssh
      port: 2222
      targetPort: 2223
  selector:
    app: drycc-builder
{{ if .Values.ingress.enabled }}
  type: "LoadBalancer"
{{ end }}
