apiVersion: v1
kind: Secret
metadata:
  name: builder-key-auth
  labels:
    heritage: drycc
type: Opaque
data:
  builder-key: {{ include "common.secrets.lookup" (dict "secret" "builder-key-auth" "key" "builder-key" "defaultValue" (randAlphaNum 64) "context" $) }}