apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-builder
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-builder
  template:
    metadata:
      labels:
        app: drycc-builder
    spec:
      {{- include "common.affinities.pods.soft" (dict "key" "app" "values" (list "drycc-builder")) | indent 6 }}
      serviceAccount: drycc-builder
      initContainers:
      - name: drycc-builder-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - netcat
          - -v
          - -a
          - $(DRYCC_MINIO_ENDPOINT)
        {{- include "builder.envs" . | indent 8 }}
      containers:
      - name: drycc-builder
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/builder:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        ports:
          - containerPort: 2223
            name: ssh
          - containerPort: 8092
            name: healthsrv
        {{- include "builder.limits" . | indent 8 }}
        {{- include "builder.envs" . | indent 8 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8092
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8092
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
            - name: builder-key-auth
              mountPath: /var/run/secrets/api/auth
              readOnly: true
            - name: builder-ssh-private-keys
              mountPath: /var/run/secrets/drycc/builder/ssh
              readOnly: true
            - name: minio-creds
              mountPath: /var/run/secrets/drycc/minio/creds
              readOnly: true
            - name: imagebuilder-config
              mountPath: /etc/imagebuilder
              readOnly: true
      volumes:
        - name: builder-key-auth
          secret:
            secretName: builder-key-auth
        - name: builder-ssh-private-keys
          secret:
            secretName: builder-ssh-private-keys
        - name: minio-creds
          secret:
            secretName: minio-creds
        - name: imagebuilder-config
          configMap:
            name: imagebuilder-config
