{{- if (.Values.global.use_rbac) -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc-builder
  labels:
    app: drycc-builder
    heritage: drycc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drycc-builder
subjects:
- kind: ServiceAccount
  name: drycc-builder
{{- end -}}
