apiVersion: v1
kind: Service
metadata:
  name: drycc-builder
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  ports:
    - name: ssh
      port: 2222
      targetPort: 2223
  selector:
    app: drycc-builder
  type: {{ .Values.service.type }}
