{{- if (.Values.global.use_rbac) -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc:drycc-builder
  labels:
    app: drycc-builder
    heritage: drycc
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list","get"]
{{- end -}}
