{{- if (.Values.global.rbac) -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc:drycc-builder
  labels:
    app: drycc-builder
    heritage: drycc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drycc:drycc-builder
subjects:
- kind: ServiceAccount
  name: drycc-builder
  namespace: {{ .Release.Namespace }}
{{- end -}}
