apiVersion: v1
kind: Service
metadata:
  name: drycc-builder
  labels:
    heritage: drycc
spec:
  ports:
    - name: ssh
      port: 2222
      targetPort: 2223
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: drycc-builder
  type: {{ .Values.service.type }}
