imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
service:
  # Provide any additional service annotations
  annotations: {}
  # Service type default to LoadBalancer
  type: ClusterIP
  # If service.type is not set to NodePort, the following statement will be ignored.
  nodePort: ""
# limitsCpu: "100m"
# limitsMemory: "50Mi"
# builder_pod_node_selector: "disk:ssd"

# When the TTL controller cleans up the Job. default: 6h
# see: https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs
ttlSecondsAfterFinished: 21600

global:
  # Role-Based Access Control for Kubernetes >= 1.5
  rbac: false
