imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"

replicas: 1

service:
  # Provide any additional service annotations
  annotations: {}
  # Service type default to LoadBalancer
  type: ClusterIP
# limitsCpu: "100m"
# limitsMemory: "50Mi"

nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  type: ""
  extraMatchLabels:
    security: "drycc-security"

podAntiAffinityPreset:
  type: "soft"
  extraMatchLabels:
    app: "drycc-builder"

# builderPodNodeSelector: "drycc.cc/node:true"

# When the TTL controller cleans up the Job. default: 6h
# see: https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs
ttlSecondsAfterFinished: 21600
# gateway customListeners
gateway:
  customListeners:
  - name: drycc-gateway-listener-builder-tcp
    port: 2222
    protocol: TCP
    allowedRoutes:
      namespaces:
        from: All

global:
  # Role-Based Access Control for Kubernetes >= 1.5
  rbac: false
