org: "drycc"
pull_policy: "Always"
docker_tag: "canary"
docker_registry: ""
# limits_cpu: "100m"
# limits_memory: "50Mi"
# builder_pod_node_selector: "disk:ssd"

global:
  # Role-Based Access Control for Kubernetes >= 1.5
  use_rbac: false

ingress:
  # Experimental feature to use Kubernetes ingress instead of Workflow's drycc-router.
  #
  # Valid values are:
  # - true: drycc-router will not be deployed. Workflow will not be usable until a Kubernetes ingress controller is installed.
  # - false: drycc-router will be deployed (default).
  enabled: false
