imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"

replicas: 1

## Enable diagnostic mode
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers
  ##
  args:
    - infinity

service:
  # Provide any additional service annotations
  annotations: {}
  # Service type default to LoadBalancer
  type: ClusterIP

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 50Mi
  # requests:
  #   cpu: 100m
  #   memory: 30Mi

nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  type: ""
  extraMatchLabels:
    security: "drycc-security"

podAntiAffinityPreset:
  type: "soft"
  extraMatchLabels:
    app: "drycc-builder"

# builderPodNodeSelector: "drycc.cc/node:true"

# When the TTL controller cleans up the Job. default: 6h
# see: https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs
ttlSecondsAfterFinished: 21600

# The following parameters will no longer use the built-in storage component.
storageBucket: "registry"
storageEndpoint: ""
storageAccesskey: ""
storageSecretkey: ""
storagePathStyle: "true"

# The following parameters will no longer use the built-in registry component.
registryHost: ""
registryUsername: ""
registryPassword: ""
registryOrganization: ""

storage:
  enabled: true

# host port for the registry proxy in the daemonset
registry:
  enabled: true
  proxy:
    port: 5555
