org: "drycc"
pull_policy: "Always"
docker_tag: "canary"
docker_registry: ""
# limits_cpu: "100m"
# limits_memory: "50Mi"
# builder_pod_node_selector: "disk:ssd"

global:
  # Experimental feature to toggle using kubernetes ingress instead of the Drycc router.
  #
  # Valid values are:
  # - true: The drycc controller will now create Kubernetes ingress rules for each app, and ingress rules will automatically be created for the controller itself.
  # - false: The default mode, and the default behavior of Drycc workflow.
  use_native_ingress: false
  # Role-Based Access Control for Kubernetes >= 1.5
  use_rbac: false
